{% set version = "3.0.2" %}

package:
  name: vitables
  version: {{ version }}

source:
  url: https://github.com/uvemas/ViTables/archive/v{{ version }}.tar.gz
  sha256: 43a965a08124fe0e1974aed27a7149cdeaf75e8ae833e95a18a94d7d5bd506c8

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pytables >=3.0
    - cython
    - pyqt
    - qtpy >=1.2.1
  run:
    - python
    - pytables >=3.0
    - pyqt
    - qtpy >=1.2.1

test:
  imports:
    - vitables.utils
  commands:
    - test -f $PREFIX/bin/vitables  # [unix]
    - if not exist %PREFIX%\\Scripts\\vitables.exe exit 1  # [win]

about:
  home: http://vitables.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'ViTables, a GUI for PyTables'
  description: |
    ViTables is a graphical tool for browsing and editing files in both PyTables
    and HDF5 format. With ViTables you can easily navigate through the data
    hierarchy, view and modify metadata, view actual data and more.
  doc_url: http://vitables.org/
  dev_url: https://github.com/uvemas/ViTables

extra:
  recipe-maintainers:
    - scopatz
