{% set name = "vitables" %}
{% set version = "3.0.0" %}
{% set sha256 = "b4067584a94b7270fe878ca53a474e0a60a9e63c43b9783991a69c3fb17ec291" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/uvemas/ViTables/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1004
  #script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  script: "{{ PYTHON }} setup.py install"
  skip: True  # [win and py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pytables >=3.0
    - cython
    - pyqt
    - qtpy >=1.2.1
    - pip
  run:
    - pytables >=3.0
    - pyqt
    - qtpy >=1.2.1

test:
  imports:
    - vitables.utils
  commands:
    - test -f $PREFIX/bin/vitables  # [unix]
    - if not exist %PREFIX%\\Scripts\\vitables.exe exit 1  # [win]

about:
  home: http://vitables.org/
  license: GPL v3
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'ViTables, a GUI for PyTables'
  description: |
    ViTables is a graphical tool for browsing and editing files in both PyTables
    and HDF5 format. With ViTables you can easily navigate through the data
    hierarchy, view and modify metadata, view actual data and more.
  doc_url: http://vitables.org/
  dev_url: https://github.com/uvemas/ViTables

extra:
  recipe-maintainers:
    - scopatz
