{% set version = "3.0.0" %}

package:
  name: vitables
  version: {{ version }}

source:
  url: https://github.com/uvemas/ViTables/archive/v{{ version }}.tar.gz
  sha256: b4067584a94b7270fe878ca53a474e0a60a9e63c43b9783991a69c3fb17ec291

build:
  number: 5
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pytables >=3.0
    - cython
    - pyqt
    - qtpy >=1.2.1
  run:
    - python
    - pytables >=3.0
    - pyqt
    - qtpy >=1.2.1

test:
  imports:
    - vitables.utils
  commands:
    - test -f $PREFIX/bin/vitables  # [unix]
    - if not exist %PREFIX%\\Scripts\\vitables.exe exit 1  # [win]

about:
  home: http://vitables.org/
  license: GPL v3
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'ViTables, a GUI for PyTables'
  description: |
    ViTables is a graphical tool for browsing and editing files in both PyTables
    and HDF5 format. With ViTables you can easily navigate through the data
    hierarchy, view and modify metadata, view actual data and more.
  doc_url: http://vitables.org/
  dev_url: https://github.com/uvemas/ViTables

extra:
  recipe-maintainers:
    - scopatz
