# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jsDh4er5+RXJZZYorlY+zwzKdfPyBJHBNV9fXprEmpapdvfFsOL1EunbCVRiwQAjaVFukdBRJ3tg5HXA2cbHrgzBqjHPWIOsbOtO7lm2RmiPiuGvu4IWNWVHd4B9I4FtLsK0kYurLJAIfM7iBBynTlEJzJGEkI4hIhb/ffn1vFHPOq+HGk+I+Oluh+Q4ZZ95Xb578E35wEmTveyMDmu/P3r+z6PfWFso3FrUn1rc6SQOTlYYrmhDc+BC9aV78CJpera0FlnQqzKfOvylyRd1l/VrVqR0UaySpnnOs8hD6NUdgDrVjUu3FVHHMvL/hTcvYJDpn4v6l3h0WekiTKuVLUmLOCGUsNC0lQw/UZUXy8XM6NvRvtORB/54suphcy0n4f3S8sWScRwlDvd/+Rj38i55qpuzk2Mx+1bBzWUQQ7jeOJgla71yfvicD84VF+AE7QImibORDXITafpRiKliYQnj7WxJ21zWPdzg2Q7VNuqO+SuyL6ZaMTTB+3MmOmbCitU+w1N+Se+XEAQVbCqab2FsIDDGTA39aVpf6KMrlk/oCBvGuikkuT3pUI3UMgQE9XhpYeoo6EJbUTvVdhQt874OHFP4HOBjTrnrj9Vj2Dn8nZVxkuvV0Lsa8+tOSbtxFlHZMPC0WjlVSOuz0IOrD0brDyhWzerqjxevnUFhwD4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
