travis:
  secure:
    BINSTAR_TOKEN: VbtBlxiY8JTO5fgtfmyxT7Fid9Ull+opr4X54oVsOXnqn2b94xil1pc7uNL0A7EB+a3+Rn2nqjCT59tIc9qa+0GZdlrnQX/cNm93alRUcLtYr0rICwsJI8txqi25DbFB593skCN2tylmLV1sBHAQoneon9fodGgHwnhgsBnBd/jXsF1jhdKdOMLjXv9tTbaWgtKaqW506rWAoCIsdfQjdu0mUS2XcRFoqUqEXeynmzCkKQ+B/Uij4noGuzxmrSly0uy0dwxsa950Y2hFBvUBMDcRPYB2nGZRSDUyn21iaSBCZRsBX3NXlrEXUm2vp78GLNCwlg2+K/UXX6eTIUzriWO1cqwq1C7EnwvDyf+tlR0X3uLUnrVbs4aKNkNgvNh+WvS5FDp99eXTKMRIqDEFtqwW3xKK8Zv7d4ix3LMGY3TAYgdWk03SwGP7EkgEhs9KGnmgFft9TxtxVjCVn4f+AOSawxdwpd7uPhdzg1pTp5CBqoSfZBsMUPsq1K57JTKYtxdO2P0POPvSlKDzvUfVr6LWjLbJnntVYNaIyJ3g16DwaLVyxvZc1Ga21/ek1KvVaj2scnIlq0xvGc/VltrIcMjmh2K/yeHrsZEdxvgSa28LmqFtIfqMjbDL831XsL2/+8Thx/9e+/mjaQdi7Lu1ch4lRk0d5MSPVt+GRzC7SmY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
