travis:
  secure:
    BINSTAR_TOKEN: xUqsEM+4EaMPF6iwqE7aqkWMLCrDrgqKztLFwehSZDbvD0q15HcVTI2w4m1lgkvb8EYXipkq/zFz/bzYLKsa9HgZxSuTE2Np4ml6Wc4FkJyj+gVAZ47JXahqg4yjyxicF9DTqVr/30H4BKK3YgeCvMSguOyMWjjFv9dc6khMXURxVz14KGHUagp2HtpKTMQRTs2EoIQE7DLeWFP/JxX0e7p1ylgKBlUg6tL1O4t2itKX3vW0TbWYas7btQnYf8jRyQfjziYxissK6Ycb4aacxTmRxAWE4zPYY72iAhPy0DO8Ry+kfnzMPepyciNyXvGtvJ86dNvbv3V9I6/mVhcTHbJkQmNuNQ4+CxqnrYMF0mCO3IhJp+/fuPl3Jma3GzUTpju8PWNDOuPbuRXLTiDUnyu/jGZJvTu1jU2lOjnQtK6PNdgddZaCpR9CPaz/xXj+HlR1nnUQej9Kb1mAO4RxMvhFG/4o3z1yB655Cb/1NeZURATnwRkT/ehdw4BS2z5syElHMABZx6+N7Gm/fFgeiRJHDX4sFYeFBICXzdmzHfGCZTVa2jYSc9+bta1616nvgppLT81Eodww1pzSu1oRMqZhJ+gYHuChgM/Qr3SyGsrog1jGPJ0X9rAb753bKi5S3APEM5GMzo4sMUFwVVYsjcBvSfjpuUhylV8ew4o3Aek=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
